name: Auto Apply Jobs

on:
  schedule:
    - cron: "0 9 * * *"   # 9:00 AM UTC
    - cron: "0 12 * * *"  # 12:00 PM UTC
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run job automation
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          # Add other required secrets or environment variables here
        run: node automation/jobRunner.js
