name: Auto Apply Jobs

on:
  schedule:
    - cron: "0 9 * * *"   # 9:00 AM UTC
    - cron: "0 12 * * *"  # 12:00 PM UTC
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install
      - run: node automation/jobRunner.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
