name: Email Monitoring Workflow

on:
  workflow_dispatch:
    inputs:
      user_id:
        description: 'User ID for the automation'
        required: true
        type: string
      email_provider:
        description: 'Email provider (gmail, outlook, etc.)'
        required: false
        type: string
        default: 'gmail'
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours

jobs:
  monitor-emails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Monitor Emails
        env:
          SUPABASE_URL: f
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          USER_ID: ${{ github.event.inputs.user_id || 'default-user' }}
          EMAIL_PROVIDER: ${{ github.event.inputs.email_provider || 'gmail' }}
         # Remove these unless needed
         # GMAIL_CLIENT_ID
         # GMAIL_CLIENT_SECRET
         # GMAIL_REFRESH_TOKEN

        run: node scripts/github-actions/monitor-emails.js

      - name: Process Email Responses
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
