name: Auto Apply Jobs

on:
  schedule:
    - cron: "0 13 * * *"  # 9 AM EDT
    - cron: "0 16 * * *"  # 12 PM EDT
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install
      - run: node automation/jobRunner.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
