name: Auto Apply
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  auto_apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Run auto apply script
        run: node automation/jobRunner.js --auto-apply
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
