name: Fetch Remote OK Jobs

on:
  schedule:
    - cron: '0 9 * * *'  # every day at 9am UTC
  workflow_dispatch:

jobs:
  fetch-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install axios googleapis nodemailer fs-extra

      - name: Fetch Remote OK Jobs
        run: node scripts/fetchRemoteOk.js
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
