import fetch from 'node-fetch';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);

async function scrapeRemoteOK() {
  const response = await fetch('https://remoteok.com/api', {
    headers: { 'User-Agent': 'Mozilla/5.0' }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch jobs: ${response.status}`);
  }

  const jobs = await response.json();

  // Skip the first item (metadata)
  const jobListings = jobs.slice(1);

  for (const job of jobListings) {
    const { id, position, company, url, tags, location } = job;

    // Insert into Supabase
    await supabase
      .from('jobs')
      .upsert({
        id,
        title: position,
        company,
        url,
        tags,
        location
      }, { onConflict: ['id'] });
  }

  console.log(`Inserted ${jobListings.length} jobs from RemoteOK`);
}

scrapeRemoteOK().catch(console.error);